(()=>{'use strict';
let state=null;const urlLang=new URLSearchParams(location.search).get('lang');/* v12: ?lang=ru|uz URL ustun (alohida indekslanadigan RU sahifa) */let lang=urlLang==='ru'||urlLang==='uz'?urlLang:(localStorage.getItem('dariko_lang')==='ru'?'ru':'uz');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setAsset(selector,url,attr='src'){if(!url)return;document.querySelectorAll(selector).forEach(el=>el.setAttribute(attr,url));}
function carousel(){document.querySelectorAll('.cms-carousel').forEach((row,i)=>{if(row.dataset.ready)return;row.dataset.ready='1';let controls=document.createElement('div');controls.className='cms-carousel-controls';controls.innerHTML='<button type="button" aria-label="Oldingi / Назад">‹</button><button type="button" aria-label="Keyingi / Вперёд">›</button>';row.parentNode.insertBefore(controls,row);controls.querySelectorAll('button').forEach((b,n)=>b.onclick=()=>row.scrollBy({left:(n?1:-1)*row.clientWidth*.95,behavior:'smooth'}));row.tabIndex=0;row.setAttribute('aria-label','Kartalar karuseli / Карусель карточек');row.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();row.scrollBy({left:(e.key==='ArrowRight'?1:-1)*row.clientWidth*.95,behavior:'smooth'})}});const update=()=>{controls.hidden=row.scrollWidth<=row.clientWidth+2};new ResizeObserver(update).observe(row);requestAnimationFrame(update);});}
function render(){if(!state)return;document.documentElement.lang=lang;window.DARIKO_LANG=lang;let seo=state.settings||{};document.title=seo['seo_title_'+lang]||(lang==='ru'?'DARIKO HR & MARKETING — Хикматулло Тураев | HR и маркетинг для бизнеса':'DARIKO HR & MARKETING — Khikmatullo Turaev | Boshqaruv & Marketing Konsaltingi');let description=document.querySelector('meta[name="description"]');if(description)description.content=seo['seo_description_'+lang]||description.content;document.querySelectorAll('[data-cms-text]').forEach(el=>{let t=state.texts[el.dataset.cmsText];if(t)el.textContent=lang==='ru'&&t.ru?t.ru:t.uz;});for(let attr of ['placeholder','aria-label','title','alt'])document.querySelectorAll('[data-cms-'+attr+']').forEach(el=>{let t=state.texts[el.getAttribute('data-cms-'+attr)];if(t)el.setAttribute(attr,lang==='ru'&&t.ru?t.ru:t.uz)});
const a=state.assets||{};setAsset('header img, footer img, .dariko-band img',a.logo);setAsset('link[rel="icon"]',a.favicon,'href');
const flags=state.flags||{};
/* v4: Kuzatuv kengashi — surat (bo'lmasa standart ikonka qoladi) va admin yoqqan bo'lsa PDF rezyume tugmasi */
document.querySelectorAll('#experts .expert-card').forEach((card,idx)=>{const i=idx+1,box=card.querySelector('.expert-photo');
 if(box){if(!box.dataset.fallback)box.dataset.fallback=box.innerHTML;const url=a['expert-'+i];
  if(url){let im=box.querySelector('img.cms-expert');if(!im){im=document.createElement('img');im.className='cms-expert';im.loading='lazy';im.decoding='async';box.replaceChildren(im)}im.src=url;im.alt=(box.getAttribute('aria-label')||'').replace(/\s*—.*$/,'')||'Ekspert surati'}
  else if(box.querySelector('img.cms-expert'))box.innerHTML=box.dataset.fallback}
 let btn=card.querySelector('.expert-resume');const pdf=a['resume-'+i];
 if(pdf&&flags['resume_visible_'+i]===true&&/^uploads\/cms-resume-[1-4]-[0-9a-f]{32}\.pdf(\?v=\d+)?$/.test(pdf)){
  if(!btn){btn=document.createElement('a');btn.className='expert-resume';btn.target='_blank';btn.rel='noopener';card.append(btn)}
  btn.href=pdf;const nm=(card.querySelector('h3')||{}).textContent||'';btn.textContent=lang==='ru'?'Резюме (PDF)':'Rezyume (PDF)';btn.setAttribute('aria-label',(lang==='ru'?'Резюме (PDF, новая вкладка): ':'Rezyume (PDF, yangi oynada): ')+nm.trim())}
 else if(btn)btn.remove()});
/* v5: Bosh sahifa "Rezyume (PDF)" kartochkasi — faqat hero_resume_visible yoqilgan VA PDF yuklangan bo'lsa DOMga qo'shiladi, aks holda umuman yo'q */
{const slot=document.getElementById('hero-resume-slot'),hp=a['hero-resume'];if(slot){
 if(hp&&flags.hero_resume_visible===true&&/^uploads\/cms-hero-resume-[0-9a-f]{32}\.pdf(\?v=\d+)?$/.test(hp)){
  let c=slot.querySelector('a.hero-resume-card');if(!c){c=document.createElement('a');c.className='hero-resume-card';c.target='_blank';c.rel='noopener';c.innerHTML='<span class="ic"><i class="fa-solid fa-file-pdf" aria-hidden="true"></i></span><span><b></b><small></small></span>';slot.replaceChildren(c)}
  c.href=hp;c.querySelector('b').textContent=lang==='ru'?'Резюме (PDF)':'Rezyume (PDF)';c.querySelector('small').textContent=lang==='ru'?'Открыть в новой вкладке':'Yangi oynada ochish';c.setAttribute('aria-label',lang==='ru'?'Резюме Хикматулло Тураева (PDF, новая вкладка)':'Khikmatullo Turaev rezyumesi (PDF, yangi oynada)')}
 else slot.replaceChildren()}}
/* v9: «Shaxsiy sahifa» — faqat personal_page_visible yoqilgan VA to'g'ri http(s) havola bo'lsa DOMga qo'shiladi, aks holda umuman yo'q */
{const slot=document.getElementById('hero-personal-slot'),pu=String((state.settings||{}).personal_page_url||'');if(slot){let ok=false;
 if(flags.personal_page_visible===true&&/^https?:\/\/[^\s<>"'`\\]+$/i.test(pu)){try{const u=new URL(pu);ok=(u.protocol==='http:'||u.protocol==='https:')&&!!u.hostname}catch(e){}}
 if(ok){let c=slot.querySelector('a.hero-resume-card');if(!c){c=document.createElement('a');c.className='hero-resume-card';c.target='_blank';c.rel='noopener noreferrer';c.innerHTML='<span class="ic"><i class="fa-solid fa-user" aria-hidden="true"></i></span><span><b></b><small></small></span>';slot.replaceChildren(c)}
  c.href=pu;c.querySelector('b').textContent=lang==='ru'?'Личная страница':'Shaxsiy sahifa';c.querySelector('small').textContent=lang==='ru'?'Открыть в новой вкладке':'Yangi oynada ochish';c.setAttribute('aria-label',lang==='ru'?'Личная страница Хикматулло Тураева (новая вкладка)':'Khikmatullo Turaev shaxsiy sahifasi (yangi oynada)')}
 else slot.replaceChildren()}}
/* v4: Bosh sahifa doirasi — faqat admin "ko'rsatish" belgisini yoqqan VA surat yuklangan bo'lsa; aks holda "KT" o'z holicha */
let hero=document.getElementById('hero-portrait');if(hero){if(!hero.dataset.fallback)hero.dataset.fallback=hero.innerHTML;
 if(a.hero&&flags.hero_photo_visible===true){let img=hero.querySelector('img.hero-photo');if(!img){img=document.createElement('img');img.className='hero-photo';hero.replaceChildren(img)}img.src=a.hero;img.alt=(hero.getAttribute('aria-label')||'').replace(/\s*surati kutilmoqda\s*$/,'')||'Khikmatullo Turaev'}
 else if(hero.querySelector('img.hero-photo'))hero.innerHTML=hero.dataset.fallback}
let theme=state.theme||{};document.documentElement.style.setProperty('--brand-navy',theme.navy||'#0b1727');document.documentElement.style.setProperty('--brand-green',theme.green||'#05a85c');let css=document.getElementById('cms-theme');if(!css){css=document.createElement('style');css.id='cms-theme';document.head.append(css)}css.textContent='header,.bg-dariko-navy{background-color:'+theme.navy+'!important}.bg-dariko-green,#contact button[type="submit"]{background-color:'+theme.green+'!important}.text-dariko-green{color:'+theme.green+'!important}';
let sets=state.settings||{};window.DARIKO_EMAIL=sets.email;document.querySelectorAll('a[href^="tel:"]').forEach(x=>{x.href='tel:'+sets.phone;if(x.textContent.includes('998'))x.textContent=sets.phone});document.querySelectorAll('a[href^="mailto:"]').forEach(x=>{x.href='mailto:'+sets.email;if(x.textContent.includes('@'))x.textContent=sets.email});document.querySelectorAll('a[href*="t.me/"]').forEach(x=>{x.href='https://t.me/'+sets.telegram;if(x.textContent.includes('@'))x.textContent='@'+sets.telegram});document.querySelectorAll('a[href*="instagram.com/"]').forEach(x=>x.href='https://instagram.com/'+sets.instagram);
if(sets.map){document.querySelectorAll('a[href^="https://maps.google.com/"]').forEach(x=>x.href='https://maps.google.com/?q='+encodeURIComponent(sets.map));document.querySelectorAll('a[href^="https://yandex.com/maps/"]').forEach(x=>x.href='https://yandex.com/maps/?text='+encodeURIComponent(sets.map))}
let map=document.querySelector('#contact iframe');if(map){const mu='https://www.google.com/maps?q='+encodeURIComponent(sets.map)+'&output=embed';map.setAttribute('data-consent-src',mu);if(map.getAttribute('src'))map.src=mu;}
document.querySelectorAll('#cms-language button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));
/* v7: features.js (bron, WhatsApp, newsletter, A/B) uchun render tugagani haqida hodisa */
document.dispatchEvent(new CustomEvent('dariko:render',{detail:{lang:lang,settings:sets}}));
}
async function start(){try{const response=await fetch('api.php?route=public',{credentials:'same-origin'});if(!response.ok)throw Error('content');state=await response.json()}catch(e){const bootstrap=document.getElementById('cms-bootstrap');if(bootstrap){try{state=JSON.parse(bootstrap.textContent)}catch(error){console.error('DARIKO initial content unavailable',error)}}}if(state){render();carousel()}}
document.querySelectorAll('#cms-language button').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('dariko_lang',lang);try{const u=new URL(location.href);if(lang==='ru')u.searchParams.set('lang','ru');else u.searchParams.delete('lang');history.replaceState(null,'',u.pathname+u.search+u.hash)}catch(e){}render()}));start();
})();
